user  www www;
worker_processes  auto;
worker_rlimit_nofile 65535;

pid logs/nginx.pid;
#error_log logs/error.log;

events {
    use epoll;
    worker_connections 65535;
}

http {
    req_status_zone server "$host" 20M;
    req_status server;

    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

    include       mime.types;
    default_type  application/octet-stream;

    #access_log	logs/access.log;
    access_log off ;
    log_format main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    server_names_hash_bucket_size 128;

    keepalive_timeout 65;
    proxy_read_timeout 300;
    client_max_body_size 30m;
    client_body_buffer_size 512k;
    client_header_buffer_size 512k;
    output_buffers 256 1024k;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 8k;
    gzip_http_version 1.1;
    gzip_types text/plain application/x-javascript text/css application/xml;

    server {
        listen 80;
        server_name localhost;

        location ~* \.html$ {
            root /data/www/check;
        }

        location /nginx_status {
            stub_status on;
            allow 127.0.0.1;
            access_log off;
            deny all;
        }
    }

    include vhosts/*;
}
